name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
      - name: Publish package
        run: ./gradlew build publish
        #uses: eskatos/gradle-command-action@v1
        #with:
        #  gradle-version: 6.8.1
        #  arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_NUMBER: ${{ steps.buildnumber.output.BUILD_NUMBER }}
